//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerToDealerDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobilMainanDealerEntities : DbContext
    {
        public MobilMainanDealerEntities()
            : base("name=MobilMainanDealerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VehiclePurchaseApprovement> VehiclePurchaseApprovements { get; set; }
        public virtual DbSet<NewPurchaseData> NewPurchaseDatas { get; set; }
    }
}
